------------------
Title: Gallup Confidence in Institutions Graphic
Author: James Vizzard
Project: Dissertation
Date: 20260611
Output: Graphics
------------------

# Load required libraries
```{r, echo = FALSE}
library(dplyr)
library(ggplot2)        # plotting functionality including attr for labels
library(ggpmisc)
library(ggrepel)        # set labels in plots
library(haven)
library(here)           # sets directory path
library(hrbrthemes)
library(knitr)          # enables running code from RMD file
library(RColorBrewer)   # RColorBrewer provides color palettes for plots
library(readr)
library(scales)
library(tidyverse)
library(viridis)

```

# Set home folder
```{r, echo = FALSE}
#here() starts at /Users/james-macbook/Data/dissertation
here::i_am("Gallup_Institutions_Confidence.Rmd")
```

# Code
```{r, echo = FALSE}


# Load Data
milcon <- read_csv("gallup_confidence_military_agg.csv")

# Plot
milcon %>%
  ggplot(aes(x=year, y=percentage, group=confidence, color=confidence)) +
    geom_line() +
    scale_y_continuous(labels = scales::percent, breaks = seq(.10, 1, by = .10)) +
    scale_x_date(breaks = c(as.Date("1993-01-20"),          # x labels = pres admins
                           as.Date("2001-01-20"),
                           as.Date("2009-01-20")),
                  date_labels = "%Y") +
    scale_color_manual(values = c("High" = "blue",          # set color of line graphs
                                "Low" = "red")) +
    theme(panel.background = element_rect(fill = "white")) +# Set background color
    theme(panel.border = element_rect(fill = "transparent", # Needed to add the border
                                    color = 1,              # Color of the border
                                    size = 1)) +            # Border width
    theme(legend.position="none") +                         # Removes legend
    geom_vline(xintercept = as.Date("1990-08-02"),          # Mark key events
              linetype = 2, color = 2, linewidth = 0.5) +
    geom_vline(xintercept = as.Date("2001-09-11"),
              linetype = 2, color = 2, linewidth = 0.5) +
    geom_vline(xintercept = as.Date("2014-06-10"),
              linetype = 2, color = 2, linewidth = 0.5) +
    labs(x = "Year", y = "Confidence",                      # Labels
         title = "Public Confidence in Military",
         subtitle = "1990-2016",
         caption = "Source: Gallup") +
    annotate("label", x = as.Date("1991-06-02"), y = 1, label = "Gulf War") +
    annotate("label", x = as.Date("2001-09-11"), y = 1, label = "9/11") +
    annotate("label", x = as.Date("2014-06-10"), y = 1, label = "ISIS") +
    annotate("label", x = as.Date("2015-10-01"), y = 0.8, label = "High") +
    annotate("label", x = as.Date("2015-10-01"), y = 0.2, label = "Low") 
ggsave(filename = "plots/lineplot_milconf.png")             # Save graphics
ggsave(filename = "plots/lineplot_milconf.pdf")

```

